on:
  schedule:
    - cron: '45 6 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - name: Dotnet-feeder
        uses: svrooij/dotnet-feeder@v1
        with:
          feed: https://svrooij.io/feed.json
          files: ./README.md
      - name: 📤 Commit and push changes, if any
        shell: pwsh
        run: |
          if (git status --porcelain | Where {$_ -notmatch '^\?\?'}) {
            echo "✅ Changes to commit"
            git config --local user.email "1292510+svrooij@users.noreply.github.com"
            git config --local user.name "GitHub Action on behalf of svrooij"
            git add README.md
            git commit -m "Refreshed posts 🤖"
            git push
          } else {
            echo "❌ No changes to commit"
          }
      # - uses: stefanzweifel/git-auto-commit-action@v4
      #   with:
      #     commit_message: Posts refreshed
      #     file_pattern: README.md

  
